# Add truecolor support
set-option -ga terminal-overrides ",xterm-256color:Tc"

# Default terminal is 256 colors
set -g default-terminal "screen-256color"

set -g focus-events on

setw -g mode-keys vi

# Use C-a instead of C-b.
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Split panes using | and -.
#bind | split-window -h
#bind - split-window -v

# Split -v S
unbind S
## bind S split-window <- this is an original line.
bind S split-window \; select-layout even-vertical

# split vertically
unbind |
## bind | split-window <- this is an original line.
bind | split-window -h \; select-layout even-horizontal

unbind '"'
unbind %

is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"
bind-key -n C-h if-shell "$is_vim" "send-keys C-h"  "select-pane -L"
bind-key -n C-j if-shell "$is_vim" "send-keys C-j"  "select-pane -D"
bind-key -n C-k if-shell "$is_vim" "send-keys C-k"  "select-pane -U"
bind-key -n C-l if-shell "$is_vim" "send-keys C-l"  "select-pane -R"
bind-key -n C-\ if-shell "$is_vim" "send-keys C-\\" "select-pane -l"
bind-key -T copy-mode-vi C-h select-pane -L
bind-key -T copy-mode-vi C-j select-pane -D
bind-key -T copy-mode-vi C-k select-pane -U
bind-key -T copy-mode-vi C-l select-pane -R
bind-key -T copy-mode-vi C-\ select-pane -l

# Reload config file.
bind r source-file ~/.tmux.conf

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'arcticicestudio/nord-tmux'

run '~/.tmux/plugins/tpm/tpm'
